name: Build PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build
        run: |
          pnpm install
          pnpm build
          git add .
          git commit -m "Automated build"
          git push
